//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareDevelopmentProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBdcsaContext : DbContext
    {
        public DBdcsaContext()
            : base("name=DBdcsaContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_final_result11> tbl_final_result11 { get; set; }
        public virtual DbSet<tbl_final_result22> tbl_final_result22 { get; set; }
        public virtual DbSet<tbl_final_result33> tbl_final_result33 { get; set; }
        public virtual DbSet<tbl_final_result33_project> tbl_final_result33_project { get; set; }
        public virtual DbSet<tbl_result11> tbl_result11 { get; set; }
        public virtual DbSet<tbl_result22> tbl_result22 { get; set; }
        public virtual DbSet<tbl_result33> tbl_result33 { get; set; }
        public virtual DbSet<tbl_result33_project> tbl_result33_project { get; set; }
        public virtual DbSet<tbl_semester11_subject> tbl_semester11_subject { get; set; }
        public virtual DbSet<tbl_semester22_subject> tbl_semester22_subject { get; set; }
        public virtual DbSet<tbl_semester33_project> tbl_semester33_project { get; set; }
        public virtual DbSet<tbl_semester33_subject> tbl_semester33_subject { get; set; }
        public virtual DbSet<tbl_students> tbl_students { get; set; }
        public virtual DbSet<tbl_studyCenter> tbl_studyCenter { get; set; }
        public virtual DbSet<tbl_users> tbl_users { get; set; }
    }
}
