//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareDevelopmentProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_result33
    {
        public int result33_id { get; set; }
        public string st_registration { get; set; }
        public string s33_course_code { get; set; }
        public Nullable<int> experment_mark1 { get; set; }
        public Nullable<int> book_mark2 { get; set; }
        public Nullable<int> viva_mark3 { get; set; }
        public Nullable<int> tma_mark1 { get; set; }
        public Nullable<int> tma_mark2 { get; set; }
        public Nullable<int> total_practical_mark { get; set; }
        public Nullable<int> total_tma_mark { get; set; }
        public string exam_term { get; set; }
        public Nullable<int> st_study_center { get; set; }
        public Nullable<System.DateTime> submit_date { get; set; }
    
        public virtual tbl_semester33_subject tbl_semester33_subject { get; set; }
        public virtual tbl_students tbl_students { get; set; }
    }
}
