//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareDevelopmentProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_students()
        {
            this.tbl_result11 = new HashSet<tbl_result11>();
            this.tbl_result22 = new HashSet<tbl_result22>();
            this.tbl_result33 = new HashSet<tbl_result33>();
            this.tbl_result33_project = new HashSet<tbl_result33_project>();
        }
    
        public int st_id { get; set; }
        [Required(ErrorMessage = "Please enter Student ID.")]
        [Display(Name = "Student ID ")]
        [RegularExpression("[0-9]{2}-[0-9]{1}-[0-9]{2}-[0-9]{3}-[0-9]{3}", ErrorMessage = "Please enter Student ID Correctly!")]
        public string st_registration { get; set; }
        [Required(ErrorMessage = "Please enter Student Name.")]
        [Display(Name = "Student Name ")]
        public string st_name { get; set; }
        [Required(ErrorMessage = "Please Select Admition Year.")]
        [Display(Name = "Admition Year ")]
        public Nullable<System.DateTime> st_admission_year { get; set; }
        [Required(ErrorMessage = "Please Select Student semester .")]
        [Display(Name = "1st Semester ")]
        public Nullable<bool> st_semester11 { get; set; }
        
        [Display(Name = "2nd Semester ")]
        public Nullable<bool> st_semester22 { get; set; }
        
        [Display(Name = "3rd Semester ")]
        public Nullable<bool> st_semester33 { get; set; }
        
        [Display(Name = "Study Center Code ")]
        public Nullable<int> st_study_center_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_result11> tbl_result11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_result22> tbl_result22 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_result33> tbl_result33 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_result33_project> tbl_result33_project { get; set; }
        public virtual tbl_studyCenter tbl_studyCenter { get; set; }
    }
}
