//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareDevelopmentProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_users
    {
        public int user_id { get; set; }
        [Required(ErrorMessage = "Please enter Study Center Name.")]
        [Display(Name = "User Name ")]
        public string user_name { get; set; }
        [Required]
        [StringLength(8, ErrorMessage = "Passward length can't be more than 8.")]
        [Display(Name = "Password Name ")]
        public string user_password { get; set; }
        [Required(ErrorMessage = "Please Select User Role.")]
        [Display(Name = "User Role ")]
        public string user_role { get; set; }
        [Display(Name = "Study Center Code ")]
        public Nullable<int> study_center_code { get; set; }
    
        public virtual tbl_studyCenter tbl_studyCenter { get; set; }
    }
}
