//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareDevelopmentProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_semester22_subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_semester22_subject()
        {
            this.tbl_result22 = new HashSet<tbl_result22>();
        }
    
        public int s22_id { get; set; }
        public string s22_course_code { get; set; }
        public string s22_course_name { get; set; }
        public string s22_course_credit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_result22> tbl_result22 { get; set; }
    }
}
