//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareDevelopmentProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_semester33_project
    {
        public int s33p_projet_id { get; set; }
        public string s33p_course_code { get; set; }
        public string s33p_course_name { get; set; }
        public string s33p_course_credit { get; set; }
    }
}
