//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareDevelopmentProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_semester11_subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_semester11_subject()
        {
            this.tbl_result11 = new HashSet<tbl_result11>();
        }
    
        public int s11_id { get; set; }
        [Required(ErrorMessage = "Please enter Course Code.")]
        [Display(Name = "Course Code ")]
        [RegularExpression("[CSE]{3}[0-9]{4}", ErrorMessage = "Please enter Course Code Correctly!")]
        public string s11_course_code { get; set; }
        [Required(ErrorMessage = "Please enter Course Code Name.")]
        [Display(Name = "Course Name ")]
        public string s11_course_name { get; set; }
        [Required(ErrorMessage = "Please enter Course Credit.")]
        [Display(Name = "Course Credit ")]
        public string s11_course_credit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_result11> tbl_result11 { get; set; }
    }
}
